# Generated by Django 3.0.2 on 2020-03-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Post Title",
                        max_length=100,
                        verbose_name="Post Title",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="Post Content",
                        max_length=100,
                        verbose_name="Post Content",
                    ),
                ),
            ],
            options={"verbose_name": "Post", "verbose_name_plural": "Posts",},
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_done",
                    models.BooleanField(
                        default=False,
                        help_text="Is Task done?",
                        verbose_name="Is Task done?",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Task Name",
                        max_length=100,
                        verbose_name="Task Name",
                    ),
                ),
                (
                    "name_ru",
                    models.CharField(
                        help_text="Task Name",
                        max_length=100,
                        null=True,
                        verbose_name="Task Name",
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        help_text="Task Name",
                        max_length=100,
                        null=True,
                        verbose_name="Task Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Task Description",
                        verbose_name="Task Description",
                    ),
                ),
                (
                    "description_ru",
                    models.TextField(
                        help_text="Task Description",
                        null=True,
                        verbose_name="Task Description",
                    ),
                ),
                (
                    "description_en",
                    models.TextField(
                        help_text="Task Description",
                        null=True,
                        verbose_name="Task Description",
                    ),
                ),
            ],
            options={"verbose_name": "Task", "verbose_name_plural": "Tasks",},
        ),
    ]
