# Generated by Django 3.0.2 on 2020-06-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="Post",),
    ]
