# Generated by Django 3.0.2 on 2020-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_delete_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Post Title",
                        max_length=100,
                        verbose_name="Post Title",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        help_text="Post Content",
                        max_length=100,
                        verbose_name="Post Content",
                    ),
                ),
            ],
            options={"verbose_name": "Post", "verbose_name_plural": "Posts",},
        ),
    ]
